### ISSUE TITLE
Choisir le niveau de difficulté

### ISSUE THREAD

**Issue by LVMVRQUXL** [LVMVRQUXL/CGG#35]
# Issue 35 : Choisir le niveau de difficulté

## Description

Permettre à l'utilisateur de définir son niveau de difficulté :
- FACILE : 5 questions
- MOYEN : 10 questions
- DIFFICILE : 15 questions

## Pré-requis

Aucun.

## Checklist

- [x] Implémentation de l'activité du niveau de difficulté
- [x] Implémentation de la navigation entre la page d'accueil et le quizz

**Comment by iReiki** [comment]
Home Screen (Pixel 3 API 28)
![image](https://user-images.githubusercontent.com/43532134/103440744-94a30500-4c48-11eb-9a61-e37b1261c579.png)
Option Screen
![image](https://user-images.githubusercontent.com/43532134/103440757-b3090080-4c48-11eb-9b23-f7a989c9b771.png)
